name: Build War

on:
  push:
    branches: [ "main" ]

jobs:
  build-war: #Job name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn clean package # Build step, compiles the code and packages it into a WAR file
      - name: Upload Jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-file
          path: target/*.jar # Save the generated WAR file from the target directory
